export let fleet=[
    {
        type:"secondi",
        name:"GENNARO'S MIXED GRILL",
        description:"Free-range pork & fennel sausage, herby marinated skirt steak, free-range chicken thigh, portobello mushroom & slow-roasted tomatoes with smoky chilli ketchup & a side of your choice",
        price:"19.95$",
        category:"secondi",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:53,
        sugar:12,
        fibre:3,
        alergyDetails:"Contains garlic, chilli",
        tag:["Gluten free","Dairy free"]
    },
    {
        type:"secondi",
        name:"TENDER ROASTED AUBERGINE",
        description:"Topped with an agrodolce ragù of tomatoes, lentils & raisins, almond yoghurt, pine nuts, rocket & pomegranate",
        price:"9.95$",
        category:"secondi",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:5,
        sugar:24,
        fibre:3,
        alergyDetails:"Contains tree nuts, gluten, soybean, garlic, celery, chilli",
        tag:["Healthy option","Dairy free","Vegetarian","Vegan"]
    },
    {
        type:"secondi",
        name:"SICILIAN CHICKEN",
        description:"Half a free-range boneless chicken in a spicy tomato, aubergine & leccino olive sauce",
        price:"14.95$",
        category:"secondi",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:108,
        carbs:5,
        sugar:62,
        fibre:3,
        alergyDetails:"Contains garlic, chilli",
        tag:["Healthy option","Dairy free"]
    },
    {
        type:"secondi",
        name:"THE JAMIE’S ITALIAN BURGER",
        description:"Prime British beef patty with pancetta, balsamic onions, artisan Westcombe Cheddar, tomato & our house special sauce in a brioche bun",
        price:"11.95$",
        category:"secondi",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:109,
        carbs:5,
        sugar:2,
        fibre:3,
        alergyDetails:"Contains sesame, milk, egg, gluten, garlic, mustard, sulphites",
        tag:null
    },
    {
        type:"secondi",
        name:"7OZ MARINATED FLASH STEAK",
        description:"Served with chargrilled portobello mushrooms, green salad, a side & a sauce of your choice: Creamy porcini; Herby garlic butter; Balsamic onion",
        price:"16.95$",
        category:"CHARGRILLED STEAKS",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:5,
        sugar:22,
        fibre:33,
        alergyDetails:"Contains milk, egg, garlic, mustard",
        tag:["Glutten free"]
    },
    {
        type:"secondi",
        name:"8OZ 35-DAY DRY-AGED SIRLOIN",
        description:"Served with chargrilled portobello mushrooms, green salad, a side & a sauce of your choice: Creamy porcini; Herby garlic butter; Balsamic onion",
        price:"16.95$",
        category:"CHARGRILLED STEAKS",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:52,
        sugar:23,
        fibre:3,
        alergyDetails:"Contains milk, egg, garlic, mustard",
        tag:["Gutten free"]
    },
    {
        type:"pasta",
        name:"CAULIFLOWER CHEESE GNOCCHI",
        description:"Organic potato gnocchi, creamy cauliflower & Gorgonzola sauce & roasted cauliflower",
        price:"6.95$",
        category:"pasta",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:52,
        sugar:23,
        fibre:3,
        alergyDetails:"Contains milk, egg, garlic, mustard",
        tag:["Gutten free"]
    },
    {
        type:"pasta",
        name:"MUSHROOM CARAMELLE",
        description:"Served with chargrilled portobello mushrooms, green salad, a side & a sauce of your choice: Creamy porcini; Herby garlic butter; Balsamic onion",
        price:"16.95$",
        category:"pasta",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:52,
        sugar:23,
        fibre:3,
        alergyDetails:"Contains milk, egg, garlic, mustard",
        tag:["Gutten free"]
    },
    {
        type:"pizza",
        name:"THE JULIETTA",
        description:"Served with chargrilled portobello mushrooms, green salad, a side & a sauce of your choice: Creamy porcini; Herby garlic butter; Balsamic onion",
        price:"16.95$",
        category:"pizza",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:52,
        sugar:23,
        fibre:3,
        alergyDetails:"Contains milk, egg, garlic, mustard",
        tag:["Gutten free"]
    },
    {
        type:"antipasti",
        name:"BREAD PLANK",
        description:"House focaccia, paysan, grissini & tapenade",
        price:"16.95$",
        category:"nibbles",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:52,
        sugar:23,
        fibre:3,
        alergyDetails:"Contains gluten, garlic, chilli, sulphites",
        tag:["Dairy free","Vegetarian","Vegan"]
    },
    {
        type:"antipasti",
        name:"CRISPY SQUID",
        description:"Parmesan-stuffed croquettes with truffle dip",
        price:"16.95$",
        category:"nibbles",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:52,
        sugar:23,
        fibre:3,
        alergyDetails:"Contains egg, gluten, garlic, chilli, mustard, molluscs",
        tag:["Dairy free"]
    },
    {
        type:"antipasti",
        name:"CRISPY SQUID",
        description:"Parmesana-stuffed croquettes with truffle dip",
        price:"16.95$",
        category:"pasta",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:52,
        sugar:23,
        fibre:3,
        alergyDetails:"Contains gluten, chilli, sulphites ",
        tag:["Healthy option","Gluten free","Dairy free","Vegetarian","Vegan"]
    },
    {
        type:"antipasti",
        name:"JAMIE’S BURRATA",
        description:"Oozy burrata with roasted squash, clementine, red chicory, fennel & pomegranate",
        price:"16.95$",
        category:"pasta",
        calories:748,
        fat:45,
        saturates:25,
        protein:80,
        salt:10,
        carbs:52,
        sugar:23,
        fibre:3,
        alergyDetails:"Contains tree nuts, milk, garlic, sulphites",
        tag:["Healthy option","Gluten free","Dairy free","Vegetarian","Vegan"]
    }

]

//         type:"",
//         description:"",
//         price:"",
//         category:"",
//         calories:,
//         fat:,
//         saturates:,
//         protein:,
//         salt:,
//         carbs:,
//         sugar:,
//         fibre:,
//         alergyDetails:""